project:
  type: website
  output-dir: docs

website:
  title: "Cortisol Concordance"
  navbar:
    left:
      - about.qmd
      - slides_moi.qmd
      
format:
  html:
    theme: slate
    css: styles.css

editor: visual

