project:
  type: website
  output-dir: docs
  
website:
  title: "Cortisol Concordance"
  navbar:
    left:
      - about.qmd
      
      
format:
  html:
    theme: journal
    css: styles.css

editor: visual

