---
title: "Cortisol Concordance: A Slide Deck"
format:
  revealjs:
    theme: moon
    transition: convex
editor: visual
execute:
  echo: false
---

## CUNY Brooklyn College PSYC 3810 Psychological Disorders II

A Presentation on Cortisol Concordance and HPA Axis Responsivity by:

E. Medrano

C. Miller

J. Navarro

###### Link Back to Home Below

[Jump to Home](https://miller-c-r.github.io/deuxieme_abpsych_group/)

## The Journal of Psychoneuroendocrinology

Stressor-Cortisol Concordance Among Individuals at Clinical High-Risk for Psychosis: Novel Findings from the NAPLS Cohort

[Link to Article](cortisol-stress-psychosis.pdf)

## Background Research

## Background {.scrollable}

1997 Schizophrenia: A neural diathesis-stress model​

This article hypothesized about the neural mechanisms involved in the effects of stressors on the diathesis. Both the behavioral and biological data indicate that stress worsens symptoms, and that the diathesis is associated with a heightened response to stressors.​

Walker EF, Diforio D. Schizophrenia: a neural diathesis-stress model. Psychol Rev. 1997 Oct;104(4):667-85. doi: 10.1037/0033-295x.104.4.667. PMID: 9337628.​

https://pubmed.ncbi.nlm.nih.gov/9337628/​

​

## Background

2001 Developmental changes in cortisol secretion in normal and at-risk youth​

A longitudinal study that measured cortisol secretion in relation to symptom development​

Walker EF, Walder DJ, Reynolds F. Developmental changes in cortisol secretion in normal and at-risk youth. Dev Psychopathol. 2001 Summer;13(3):721-32. doi: 10.1017/s0954579401003169. PMID: 11523856.​ https://pubmed.ncbi.nlm.nih.gov/11523856/​

​

​

## Background {.scrollable}

2017 The neural diathesis-stress model of schizophrenia revisited: An update on recent findings considering illness stage and neurobiological and methodological complexities​

Investigates evidence on the premorbid periods of psychosis, and our more nuanced understanding of (HPA) axis function and its association with neurodevelopmental, epigenetic, neurotransmitter, and inflammatory processes, as well as brain structure and function. ​

A review of relevant research published since the 2008 update of the model. Propose an extended neural diathesis-stress model that addresses the broader neurobiological context of stress psychobiology in psychosis progression. ​

Marita Pruessner, Alexis E. Cullen, et. al . The neural diathesis-stress model of schizophrenia revisited: An update on recent findings https://www.sciencedirect.com/science/article/pii/S0149763416301713)​

​

## Key Terms {.scrollable}

**Prodrome/ Prodromal**

-   APA defines prodrome as an early symptom or symptoms of a mental or physical disorder. A prodrome frequently serves as a warning or premonitory sign that may, in some cases, enable preventive measures to be taken. ​

**Diathesis**

-   predisposition toward a particular state or condition and especially one that is abnormal or diseased (Merriam-Webster, n.d.)​

**Endocrine Sytem**​

-   The endocrine system consists of glands located throughout the body; Hormones made by the glands and released into the bloodstream or the fluid surrounding cells; and Receptors in various organs and tissues that recognize and respond to the hormones.​

​

## Key Terms​ {.scrollable}

**Hypothalamic-Pituitary-Adrenal (HPA) Axis​**

​

Hypothalamic-Pituitary-Adrenal (HPA) Axis​

Involves the The Hypothalamus, Pituitary Gland and Adrenal Glands​

Activates stress systems on exposure to a stressor​

Feedback loops, restrain the responsiveness of the HPA axis to reset the system to baseline activity ...​

the forward loop prepares the organism to anticipate and respond optimally to a threat, while the feedback loop ensures returning efficiently to a homeostatic balance when it is no longer challenged (for review see de Kloet et al., 1998).​

It has been shown that the negative feedback control of the HPA axis can become dys-regulated, particularly following periods of chronic stress. (Jubb, 2016). ​

​

Neural Diathesis Stress Model​

The diathesis stress model postulates the interaction between a genetic vulnerability or predisposition and adverse life events in the genesis of \[a disorder\] (Ladd, Charlotte O., Huot, Rebecca L. , et. al, 2000)​

​## A Brief Review of the Hypothalamus, Pituitary Gland and the Endocrine System​

## The Endocrine System

The endocrine system is made up of all of the body's different hormones, regulates all biological processes in the body​

This includes development of the brain and nervous system, the growth and function of the reproductive system, as well as the metabolism and blood sugar levels.(EPA, 2023).​

It includes the hypothalamus, pituitary adrenals and other glands.​

##  {background-image="endocrine_system.jpg" background-size="600px"}

## The Hypothalamus & The Pituitary Gland

##  {background-image="yale_brain.png" background-size="800px"}

## The Hypothalamus

The hypothalamus links our nervous and endocrine systems together, it drives the endocrine system (EPA , 2023) ​

​

The hypothalamus monitors internal systems keeping homeostasis through its neural connections, controlling the release of various hormones.​

​

It regulates sleep, hunger, thirst, body temperature, blood pressure, hormone secretion and water balance​

​

## The Pituitary Gland

## The Pituitary Gland Part I {.scrollable}

The pituitary gland is intimately linked to the hypothalamus​

It is sometimes designated as the master gland. It is about the size of an acorn. The pituitary is actually two glands in one: The anterior pituitary, the posterior pituitary​

The anterior pituitary contains endocrine cells which produce several hormones under tight control by the neurons in the hypothalamic nuclei(Jubb, 2016):

1.  adrenocorticotropic hormone \[ACTH\]
2.  thyroid‐stimulating hormone \[TSH\]
3.  follicle‐stimulating hormone \[FSH\]
4.  luteinizing hormone \[LH\]
5.  growth hormone \[GH\]
6.  prolactin \[PRL\])

##  {background-image="jubb_hpa_axis.png" background-size="600px"}

**The HPA Axis**

## HPA Axis {.scrollable}

In contrast to the fight or flight response, the HPA axis is slower, a more protracted response. \[to stress\] (Jubb, 2016).​

The release of CRH from the hypothalamus leads to stimulation of the anterior pituitary and ACTH secretion and in turn of corticosterone from the adrenals. The activational effects of the HPA axis are counteracted by the negative feedback inhibitory effects of glucocorticoid receptors expressed in the hippocampus, hypothalamus, and pituitary(Jubb, 2016).​

​

## Question {.scrollable}

Broad Question- Elevations in basal cortisol levels have been reported among individuals at-risk for psychosis, the extent to which this represents hyperresponsivity of the hypothalamic-pituitary-adrenal (HPA) axis to psychosocial stressors encountered in the natural environment is currently unclear.​

Specific Question- They examined stressor-cortisol concordance among youth at clinical high-risk (CHR) for psychosis in the North American Prodrome Longitudinal Study 2 (NAPLS 2) and the relationship with clinical outcome.​

Specific Question- Determining the extent to which HPA axis responsivity in at-risk youth predicts clinical outcome is important, as such work might ultimately help to identify individuals at increased risk of illness progression by virtue of being more sensitive to the effects of psychosocial stress, enabling targeted interventions.​

​

## Hypothesis {.scrollable}

They hypothesized that CHR youth who later converted to psychosis would show (a) greater exposure and distress in relation to psychosocial stressors, (b) elevated basal cortisol, and (c) higher stressor-cortisol concordance relative to healthy controls; ​

Alternative Hypothesis ---\> CHR non-converters would be intermediate to CHR converters subgroups and healthy controls (i.e., converters \> positive symptom progression \> symptomatic \> remitted \> controls) on these measures. ​

For example, categorization of clinical high-risk subgroups at the two-year follow-up were as follow converters \> positive symptom progression \> symptomatic \> remitted \>controls. ​

## Logic and Design {.scrollable}

Cullen et. al aimed to further characterize the nature of HPA axis abnormalities among individuals at-risk for psychosis by examining psychosocial stressors, basal cortisol, and the concordance between these measures in a large sample of CHR youth categorized according to clinical status at the two-year follow-up.​

They utilized data from the North American Prodrome Longitudinal Study 2 (NAPLS 2) and investigated whether psychosocial stressors, basal cortisol levels, and stressor-cortisol concordance (i.e., the magnitude of association between psychosocial stressors and cortisol) at the baseline assessment differed across healthy controls and CHR subgroups defined on the basis of their clinical presentation at the two-year follow-up (remitted, symptomatic, progression of positive symptoms, and converted to psychosis).​

## Methods

Subjects:​

662 Participants​

12-35 years at age of recruitment​

Two groups: CHR subjects (clinical high-risk) for psychosis in the North American Prodrome Longitudinal Study 2 (NAPLS 2) and Healthy controls​

​

## Methods {.scrollable}

Three stress measures were utilized.

Stress measures were recorded using:​

-   58 item, Daily Stress Inventory,​

-   Life events were assessed via the Psychiatric Epidemiology Research Interview Life Events Scale that was modified to exclude life events of lesser relevance to youth (divorce and financial losses) ​

-   Lastly participants completed the Childhood Trauma and Abuse Scale, a semi-structured interview examining experiences of physical, sexual, and psychological abuse and emotional neglect prior to the age of 16. ​

​

## Methods

Researchers assessed HPA axis function using basal salivary cortisol collected in the laboratory, as it is more reliable and, unlike home sampling methods, unlikely to be influenced by confounding factors such as exercise. ​

Prodromal symptoms were assessed via the Structured Interview for Prodromal Syndromes (SIPS) at 12- and 24-month follow-up assessments and used to categorise CHR subgroups​

## Methods cont'd {.scrollable}

​

At the research session subjects provided 3 saliva samples, one per hour with a mean salivary cortisol value subsequently derived when two or more samples were available.​

​

​

Researchers created a Five- level categorical variable consisting of​

Cortisol collected before the stress measurement​

Cortisol same day as stressor assessments​

Cortisol 1-10 days after stress measurement​

Cortisol 11-30 days after​

Cortisol \> 30 days after​

​

​

## CHR Youth versus Healthy Controls​

## CHR Subjects {.scrollable}

Exclusion criteria​

Axis-1 psychotic disorder (DSM IV Mood, Psychotic...disorders)​

Permitted treatment with antipsychotic medication provided full psychotic symptoms were not present at the time of medication commencement​

​

Met criteria for one or more prodromal syndromes​

Attenuated psychotic symptoms​

Brief intermittent psychotic symptoms​

Substantial functional decline combined with a first degree relative with a psychotic disorder or schizotypal personality disorder in individuals younger than 18 years.​

​

​

## CHR Subjects

​

Help Seeking​

​

Initial assessment​

Conducted by clinically trained interviewers​

Prodromal syndromes were assessed using the **Criteria of Prodromal Syndromes** (COPS) based on the Structured Interview for Prodromal Syndromes(SIPS)​

Psychiatric diagnoses were determined via the **Structured Clinical Interview (SCID) for DSM-IV**​

​

## Healthy Controls

Recruited from the community​

No personal history or first-degree relative with psychosis​

Did not meet prodromal syndrome criteria​

Exclusion criteria​

Non psychotic psychiatric disorders were permitted​

Substance dependence in the past 6 months​

IQ \< 70​

Neurological disorder​

​

## Results

##  {background-image="lapse_time.png" background-size="800px"}

Lapse of Time(Days) Between Cortisol Sample Collection and Stressor Assessment

##  {background-image="95_percent_confidence_intervals.png" background-size="800px"}

Confidence Intervals Representing the Magnitude of Stressor Cortisol Concordance

## Results

Of the 457 CHR individuals included in the current study: ​

134 (29.3%) showed a remission of CHR symptoms​

130 (28.4%) remained symptomatic​

124 (27.1%) experienced a progression of positive symptoms​

69 (15.1%) converted to psychosis. ​

## Result {.scrollable}

None of the CHR subgroups showed significant hyper- or hypo-responsivity of the HPA axis in response to psychosocial stressors encountered in the natural environment when compared to controls.​

Stressor-cortisol concordance was substantially higher among CHR converters compared to all other CHR subgroups. ​

## Inferences {.scrollable}

Stress measures versus basal cortisol​

-   Daily stressor distress was significantly associated with cortisol in controls and CHR converters​

-   None of the stress measures: 58-item Daily Stress Inventory ;Psychiatric Epidemiology Research Interview Life Events Scale; Childhood trauma and abuse scale, were significantly associated with cortisol in the CHR remitted, symptomatic or progressed subgroups​

## Inferences {.scrollable}

In conclusion, in line with their hypothesis, while **all CHR subgroups** showed increased psychosocial stress exposure and distress relative to controls, ​

Only those who later converted to psychosis **(CHR converters)** were characterized by significantly elevated basal cortisol levels. ​

Moreover, only CHR converters showed a higher magnitude of **stressor-cortisol concordance** compared to controls, ​

although confidence intervals overlapped considerably between these two groups. These findings do not support the notion that all individuals at CHR for psychosis show HPA hyperresponsiveness to psychosocial stressors. Instead, **CHR individuals vary** in their response to stressor exposure/distress, perhaps driven by genetic or other vulnerability factors.​

​

## Inferences

Exact mechanisms underlying HPA responsivity to stress are unknown and likely complex​

There are individual differences in responsivity that are likely due to genetic variants​

FKBP5, CRHR1, NR3C1, NR3C2 that modify the effect of acute and chronic stress/trauma on cortisol levels in healthy adolescents and adults and patients with psychosis​

​

## Limitations {.scrollable}

Individual CHR subgroups were small (particularly the converted group) and reduced their ability to detect statistically significant associations between psychosocial stressors and cortisol.​

They did not adjust for multiple comparisons in their primary analyses examining stressor-cortisol concordance and some significant associations arose by chance. However, they tested specific a priori hypotheses and interested in the overall pattern of stressor-cortisol concordance rather than statistical significance. Moreover, they adjusted for a range of potential confounders which, had we not accounted for these variables, would have led to spurious associations.​

## Limitations {.scrollable}

Another limitation is that a small proportion of participants (16%), experienced a long delay (\> two months) between baseline assessment visits, which led to a large lapse-of-time between completion of psychosocial stressor assessments and cortisol collection.​

One major limitation is that they only examined three stressor types. There are other stressors such as urbanicity, neighborhood cohesion, and socioeconomic deprivation relevant to psychosis that might impact the HPA axis function. Considering this, it is possible that examining a wider range of stressors might yield different patterns of stressor-cortisol concordance across CHR subgroups. ​

Their findings are also specific to basal salivary cortisol, other measures such as plasma cortisol, salivary diurnal or awakening cortisol profiles may have produced different results.​

​

## Limitations {.scrollable}

They did not account for psychosocial stressors and other confounding factors/events that may have occurred in the time between baseline and follow-up. It is possible that stressor-cortisol concordance at follow-up does in fact distinguish between CHR subgroups, but that their measure at baseline was too distal to outcome. ​

Lastly, CHR individuals are at elevated risk for a wide range of psychiatric disorders, particularly depression and anxiety (Addington et al., 2017; Addington et al., 2019), and so worsening of prodromal symptoms/transition to psychosis is only one of several potential outcome measures, all of which will inevitably involve more false negatives the shorter the follow-up period. A recent study suggested that well-established risk factors are better at predicting poor functioning in CHR populations than transition to psychosis (Zhang et al., 2019). The extent to which stressor-cortisol concordance at baseline is associated with other non-psychotic disorders and functioning at follow-up is therefore warranted.​

## Future Research

How to approach future research​

-   Varying assessments of cortisol, in collection​

-   Neuroimaging of various structures involved in mediating HPA axis function​

-   Pituitary affinity for glucocorticoid receptors​

-   Differences between sex​

-   Polymorphism in genes for glucocorticoid receptor proteins​

​

​

​

## Group Selected Article {.scrollable}

A meta-analysis of blood and salivary cortisol levels in first-episode psychosis and high-risk individuals​ (2021)

[A Link to Meta-analysis of Blood and Salivary Cortiool levels Article](https://doi.org/10.1016/j.yfrne.2021.100930)

​

## Why we chose this article {.scrollable}

Previous meta-analyses have only addressed single parameters of the HPA axis activity and have not considered cortisol levels in blood and saliva separately as well as their association with other hormonal and metabolic alterations reported in this population, including impaired glucose homeostasis (Pillinger et al., 2017) and altered levels of DHEA or DHEA-S (Misiak et al., 2018). ​

Another shortcoming of previous research is the lack of a systematic comparison of baseline cortisol levels and cortisol levels in response to stimulation. ​

Lastly, there is some evidence that unaffected relatives of individuals with psychosis show increased emotional reactivity to daily life stress, increased ACTH levels in response to stress, increased pituitary volume and reduced hippocampal volume (Aiello et al., 2012). ​

​

​

## Introduction {.scrollable}

The hypothalamic-pituitary adrenal (HPA) axis is one of the biological systems responsible for stress response ​

Evidence suggest the activity of the HPA axis might be involved in the pathophysiology of psychosis ​

Previous meta-analyses of the HPA axis activity demonstrated the following alterations​

1)  blunted cortisol awakening response (CAR) in first-episode psychosis (FEP) and schizophrenia (Berger et al., 2016)​

2)  attenuated cortisol response to social stress in schizophrenia(Ciufo- lini et al., 2014)​

3)  increased morning cortisol levels in blood and saliva of individuals with schizophrenia and FEP (Girshkin et al., 2014)​

4)  increase baseline cortisol levels in blood of individuals with FEP (Hubbard and Miller, 2019)​

5)  increased baseline cortisol levels in saliva of individuals at clinical high risk (CHR) of psychosis (Chaumette et al., 2016)​

This study performed a meta-analysis on baseline cortisol levels and cortisol levels in response to stimulation in the blood and saliva ​

​

​

## Hypothesis

Hypothesis- They aimed to perform a meta-analysis investigating baseline cortisol levels and cortisol levels in response to stimulation in blood and saliva in subjects with first-episode psychosis (FEP), CHR individuals, as well as unaffected relatives of individuals with schizophrenia, taking into consideration a number of potential moderators such as the levels of glucose, insulin, DHEA and DHEA-S as well as lipid profile. ​

​

​

## Methods and Results

Methods​

47 studies were included in the meta-analysis​

Subjects ​

These studies included:​

1327 patients with FEP (range of mean age: 20.6 -- 33.7 years, range of percentage of males: 45.2 -- 100%)​

932 CHR individuals (range of mean age: 14.2 -- 24.5 years, range of percentage of males: 42.9 -- 100%)​

242 FHR(Individuals at familial risk) individuals (range of mean age: 13.3 -- 39.3 years, range of percentage of males: 32.4 -- 73.7%) ​

2203 healthy controls (range of mean age: 13.1 -- 37.3 years, range of percentage of males: 38.1 -- 100%). ​

​

## Results

Unstimulated blood cortisol

-   27 studies investigated levels of blood cortisol

-   Blood cortisol levels were significantly higher in patients with FEP

-   Not individuals at high risk for psychosis compared to healthy controls

## Results

Unstimulated salivary cortisol

-   18 studies utilized for investigation of salivary cortisol levels

-   There were no significant differences in unstimulated salivary cortisol levels between patients with FEP and healthy controls

-   No significant differences were found between CHR converters and non converters

-   further analysis with the leave one out sensitivity analysis revealed salivary cortisol levels were significantly higher in CHR individuals compared to healthy controls

## Results

CAR (Cortisol Awakening Response)​

9 studies were used to investigate the CAR​

4 studies included CHR individuals ​

1 study included FHR individuals ​

5 were based on patients with FEP​

CAR was significantly attenuated in subjects with FEP​

Not in high-risk individuals​

​

## Results {.scrollable}

-   Blood cortisol levels were not associated with between group differences in age, sex

-   Effect size estimates for blood cortisol levels are significantly associated with those for the levels of glucose and insulin

-   Consistent with previous studies regarding abnormal glucose homeostasis parameters in unmedicated patients with FEP enhanced activity of the HPA axis contributes to impaired glucose homeostasis

## Contrasting the Two articles {.scrollable}

The Pruessner et al meta-analysis was able to compare First Episode Psychosis (FEP) patients with CHR individuals and healthy controls. ​

The previous study limited its investigation to salivary cortisol as it relates to symptom progression in CHR individuals​

The Pruessner et al meta-analysis also included first degree relatives that were categorized as unaffected. ​

Regarding first degree relatives the study by Pruessner et al. (2014) revealed a blunted CAR in children, who were relatives of individuals with schizophrenia, suggesting that the CAR might be associated with familial liability to psychosis.​

​

## Discussion Questions {.scrollable}

This research has shed light on the complexity of how endocrine pathways affect and/or determine behaviors, therefore playing a role in neuropsychiatric disorders. Let's talk more about this.​ ​

Just to recap from what we've learned in class- What are some types of psychosocial stressors? Hint: Remember a psychosocial stressor can include anything that translates to a perceived threat to our social status, social esteem, respect, acceptance within a group, threat to our self-worth, or a threat that we feel we have no control over, stress measure slides​

What are some indicators of the early onset of psychosis? Why do you think early identification/intervention is an important part of treatment?\
Hint: Changes in Affect, Cognition (Thinking), Sense of Self, Others or the World, Physical​

What role does stress play when considering critical periods of development and risk for psychosis? Is psychosocial stress alone necessary and sufficient to trigger the onset of psychosis? Hint: Neural diathesis model​

Do you think sex differences are of relevance to the pathophysiology of psychosis? Why or why not? Is it possible that there are sex differences in cortisol responses? Hint: The authors noted the participant sex as a potential confounder. ​

## References {.scrollable}

​

Berger, M., Kraeuter, A.K., Romanik, D., Malouf, P., Amminger, G.P., Sarnyai, Z. Cortisol awakening response in patients with psychosis: Systematic review and meta-analysis,Neuroscience & Biobehavioral Reviews, Volume 68, 2016,Pages 157-166. ISSN 0149-7634,https://doi.org/10.1016/j.neubiorev.2016.05.027. (https://www.sciencedirect.com/science/article/pii/S0149763416300549)​

Błażej Misiak, Marita Pruessner, Jerzy Samochowiec, Michał Wiśniewski, Artur Reginia, Bartłomiej Stańczykiewicz. A meta-analysis of blood and salivary cortisol levels in first-episode psychosis and high-risk individuals, Frontiers in Neuroendocrinology, Volume 62, 2021,100930, ISSN 0091-3022, https://doi.org/10.1016/j.yfrne.2021.100930.​

Chaumette, B., Kebir, O., Mam-Lam-Fook, C., Morvan, Y., Bourgin, J., Godsil, B. P., Plaze, M., Gaillard,R., Jay, T. M., Krebs, M. O. Salivary cortisol in early psychosis: New findings and meta-analysis. Psychoneuroendocrinology. Volume 63.2016. Pages 262-270. ISSN 0306-4530, https://doi.org/10.1016/j.psyneuen.2015.10.007. (https://www.sciencedirect.com/science/article/pii/S0306453015009555)​

Ciufolini, S., Dazzan, P., Kempton, M.J., Pariante, C., Mondelli, V., 2014. HPA axis response to social stress is attenuated in schizophrenia but normal in depression. Evid. from a meta-analysis Exist. Stud. 47, 359--368.​

Cullen et. al. Stressor-Cortisol Concordance Among Individuals at Clinical High-Risk for Psychosis: Novel Findings from the NAPLS Cohort. Psychoneuroendocrinology. 2020 May;115:104649. doi: 10.1016/j.psyneuen.2020.104649. Epub 2020 Mar 7. PMID: 32197198; PMCID: PMC7193890.​

Dunlavey CJ. Introduction to the Hypothalamic-Pituitary-Adrenal Axis: Healthy and Dysregulated Stress Responses, Developmental Stress and Neurodegeneration. J Undergrad Neuroscience Education. 2018 Jun 15;16(2):R59-R60. PMID: 30057514; PMCID: PMC6057754.​

​

​

​

## References {.scrollable}

​

​

Girshkin, S.L. Matheson, A.M. Shepherd, M.J. Green. Morning cortisol levels in cortisol levels in schizophrenia and bipolar disorder: a meta-analysis. Psychoneuroendocrinology, 49 (2014), pp. 187-206, 10.1016/j.psyneuen.2014.07.013​

Hubbard, D. B., Miller,B. J. Meta-analysis of blood cortisol levels in individuals with first-episode psychosis. Psychoneuroendocrinology. Volume 104. 2019. Pages 269-275. ISSN 0306-4530. https://doi.org/10.1016/j.psyneuen.2019.03.014. (https://www.sciencedirect.com/science/article/pii/S030645301830979X)​

Jubb. (2016). Molecular neuroendocrinology : from genome to physiology (Murphy & H. Gainer, Eds.). Wiley Blackwell.​

Ladd, Charlotte O., Huot, Rebecca L. , et. al,(2000). Long-term behavioral and neuroendocrine adaptations to adverse early experience, Progress in Brain Research , 122, 81-103, ISSN 0079-6123, ISBN 9780444500496, https://doi.org/10.1016/S0079-6123(08)62132-9.​

Lupien, Maheu, F., Tu, M., Fiocco, A., & Schramek, T. E. (2007). The effects of stress and stress hormones on human cognition: Implications for the field of brain and cognition. Brain and Cognition, 65(3), 209--237. https://doi.org/10.1016/j.bandc.2007.02.007​

Marita Pruessner, Alexis E. Cullen, Monica Aas, Elaine F. Walker, The neural diathesis-stress model of schizophrenia revisited: An update on recent findings considering illness stage and neurobiological and methodological complexities, Neuroscience & Biobehavioral Reviews, Volume 73, 2017,Pages 191-218,ISSN 0149-7634,https://doi.org/10.1016/j.neubiorev.2016.12.013​

Merriam-Webster. (n.d.). Diathesis. In Merriam-Webster.com dictionary. Retrieved October 21, 2023, from https://www.merriam-webster.com/dictionary/diathesis​

United States Environmental Protection Agency. (2023, March 13). Overview of the endocrine system \| US EPA. https://www.epa.gov/endocrine-disruption/overview-endocrine-system ​

Walker EF, Walder DJ, Reynolds F. Developmental changes in cortisol secretion in normal and at-risk youth. Developmental Psychopathology. 2001 Summer;13(3):721-32. doi: 10.1017/s0954579401003169. PMID: 11523856.​

​

​

​
